[package]
name = "client"
description = "Simple pingxelflut client"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
socket2 = { version = "0.5.7", features = ["all"] }
pingxelflut = { path = "../pingxelflut" }
